[package]
name = "cernan"
version = "0.3.3"
authors = ["Brian L. Troutwine <blt@postmates.com>"]
build = "build.rs"

[dependencies]
quantiles = "0.1.5"
lru-cache = "0.0.7"
chrono = "0.2"
lalrpop-util = "0.12.0"
string_cache = "0.2.21"
clap = "2.10.0"
fern = "0.3.5"
log = "0.3.6"
dns-lookup = "0.2.1"
toml = "0.2.0"
notify = "2.6.3"
serde = "0.8"
bincode = "0.6.0"

[dev-dependencies]
tempdir = "0.3"
quickcheck = "0.3"
rand = "0.3"

[build-dependencies]
lalrpop = "0.12.0"
serde_codegen = "0.8"

[profile.release]
lto = true
