[package]
authors = ["Brian L. Troutwine <blt@postmates.com>",
           "Tom Santero <tom.santero@postmates.com>"]
description = "A telemetry and logging aggregation server."
keywords = ["statsd", "graphite", "telemetry", "logging", "metrics"]
license = "MIT"
name = "cernan"
readme = "README.md"
repository = "https://github.com/postmates/cernan"
version = "0.5.8"

[[bin]]
name = "cernan"
doc = false

[dependencies]
byteorder = "1.0"
chrono = "0.3"
clap = "2.20.5"
fern = "0.3.5"
flate2 = "0.2"
glob = "0.2.11"
hopper = "0.2.1"
hyper = "0.10"
lazy_static = "0.2.1"
libc = "0.2"
log = "0.3.6"
lua = "0.0.10"
protobuf = "1.2"
quantiles = "0.3"
rand = "0.3"
rusoto = {version = "0.23.1", features = ["firehose"]}
seahash = "3.0"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
toml = "0.2.0"
uuid = {version = "0.4", features = ["v4"]}

[dev-dependencies]
tempdir = "0.3"
quickcheck = "0.4"

[profile.dev]
codegen-units = 4

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
