[package]
authors = ["Brian L. Troutwine <blt@postmates.com>",
           "Tom Santero <tom.santero@postmates.com>"]
description = "A telemetry and logging aggregation server."
keywords = ["statsd", "graphite", "telemetry", "logging", "metrics"]
license = "MIT"
name = "cernan"
readme = "README.md"
repository = "https://github.com/postmates/cernan"
version = "0.7.13-pre"

[[bin]]
name = "cernan"
doc = false

[dependencies]
byteorder = "1.0"
chrono = "0.4"
clap = "2.20.5"
coco = "0.2.0"
elastic = "0.13"
elastic_types = "0.19"
fern = "0.4"
flate2 = "0.2"
glob = "0.2.11"
hopper = { git = "https://github.com/postmates/hopper.git", branch = "introduce_zlo" }
hyper = "0.10"
hyper-native-tls = "0.2"
lazy_static = "0.2.1"
libc = "0.2"
log = "0.3.6"
lua = { git = "https://github.com/blt/rust-lua53.git", branch = "master" }
openssl-probe = "0.1"
protobuf = "1.2"
quantiles = { git = "https://github.com/postmates/quantiles.git", branch = "ckms_insertion_perf_improvement", features = ["serde_support"] }
regex = "0.2"
rusoto_core = {version = "0.25.0"}
rusoto_firehose = {version = "0.25.0"}
seahash = "3.0"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.4"
url = "1.4.0"
uuid = {version = "0.5", features = ["v4"]}
chan-signal = "0.3.1"

[dev-dependencies]
tempdir = "0.3"
quickcheck = "0.4"

[profile.dev]
codegen-units = 4

[profile.release]
lto = true
codegen-units = 1
