[package]
authors = ["Brian L. Troutwine <blt@postmates.com>",
           "Tom Santero <tom.santero@postmates.com>"]
description = "A telemetry and logging aggregation server."
keywords = ["statsd", "graphite", "telemetry", "logging", "metrics", "systemd"]
license = "MIT"
name = "cernan"
readme = "README.md"
repository = "https://github.com/postmates/cernan"
version = "0.8.3"

[[bin]]
name = "cernan"
doc = false

[dependencies]
byteorder = "1.0"
chrono = "0.4"
clap = "2.27"
coco = "0.3"
elastic = "0.20"
elastic_types = "0.20"
fern = "0.4"
flate2 = "0.2"
glob = "0.2.11"
hopper = "0.3"
hyper = "0.10"
lazy_static = "0.2.1"
libc = "0.2"
log = "0.3"
lua = { git = "https://github.com/blt/rust-lua53.git", branch = "master" }
openssl-probe = "0.1"
protobuf = "1.4"
quantiles = { version = "0.6", features = ["serde_support"] }
regex = "0.2"
rusoto_core = "0.29"
rusoto_firehose = "0.29"
seahash = "3.0"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_json = "1.0"
systemd = { url = "https://github.com/ibotty/rust-systemd", branch = "await-new-records" }
toml = "0.4"
url = "1.6"
uuid = {version = "0.5", features = ["v4"]}
chan-signal = "0.3"

[dev-dependencies]
tempdir = "0.3"
quickcheck = "0.4"

[profile.dev]
codegen-units = 4

[profile.release]
lto = true
codegen-units = 1
