[package]
name = "cernan"
version = "0.1.5"
authors = ["Brian L. Troutwine <blt@postmates.com>"]
build = "build.rs"

[dependencies]
docopt = "0.6.80"
histogram = "*"
hyper = "0.9.6"
lru-cache = "0.0.7"
mime = "0.2.0"
rustc-serialize = "0.3.19"
time = "0.1"
url = "1.1.1"
regex = "0.1"
lalrpop-util = "0.11.0"

[build-dependencies]
lalrpop = "0.11.0"

[profile.release]
lto = true
