[package]
name = "cernan"
version = "0.4.2"
authors = ["Brian L. Troutwine <blt@postmates.com>"]
build = "build.rs"

[[bin]]
name = "cernan"
doc = false

[dependencies]
bincode = "0.6.0"
chrono = "0.2"
clap = "2.10.0"
dns-lookup = "0.2.1"
flate2 = "0.2"
fnv = "1.0.5"
lazy_static = "0.2.1"
log = "0.3.6"
notify = "2.6.3"
quantiles = "0.2.0"
rusoto = {version = "0.17.0", features = ["firehose"]}
serde = "0.8"
serde_json = "0.8"
toml = "0.2.0"
rand = "0.3"
slog = "1.2.0"
slog-stdlog = "1.1.0"
slog-term = "1.3.2"

[dev-dependencies]
tempdir = "0.3"
quickcheck = "0.3"

[build-dependencies]
serde_codegen = "0.8"

[profile.dev]
codegen-units = 4

[profile.release]
lto = true
codegen-units = 4
