data-directory = "data/"

# cernan listens on two telemetry protocols, statsd and graphite. The following
# two configuration items set the ports cernan will listen on.
[statsd]
port = 8125

[graphite]
enabled = true
port = 2003

# There is one global timing interval on which cernan will sync from its sources
# to its sinks. This value is in seconds.
flush-interval = 10

[tags]
source = "cernan"

[[file]]
path = "example.log"

# sinks
[console]
bin_width = 5

[null]

[wavefront]
port = 2878
host = "127.0.0.1"
bin_width = 1
